version: '3.8'
services:
  rating-service:
    build:
      context: ./RatingService
    ports:
      - "5000:80"

  notification-service:
    build:
      context: ./NotificationService
    ports:
      - "8080:8080"