services:
  rating-service:
    build:
      context: ./RatingService
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"